[[redirects]]
  from = "/blog/:slug"
  to = "/blog/:slug.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/car-buying-concierge-chicago"
  to = "/car-buying-concierge-chicago.html"
  status = 200
